version: '2'

services:

    web-dev:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
            
    server-dev:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"

    web-prod:
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        ports:
            - "3000:3000"
                    
    server-prod:
        build:
            context: ./backend
            dockerfile: Dockerfile.prod
        ports:
            - "8080:8080"